[xdebug]
xdebug.mode=develop,debug
;xdebug.start_with_request=trigger
xdebug.start_with_request=yes
xdebug.discover_client_host=true
xdebug.client_port=9003
xdebug.client_host=host.docker.internal

;todo
xdebug.idekey=${XDEBUG_IDE_KEY}

xdebug.log=/var/log/xdebug.log
xdebug.var_display_max_children=128
xdebug.var_display_max_data=1024
xdebug.var_display_max_depth=10