services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    clickhouse:
        image: clickhouse/clickhouse-server:23.8-alpine
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - clickhouse_data:/var/lib/clickhouse
        environment:
            CLICKHOUSE_DB: laravel
            CLICKHOUSE_USER: default
            CLICKHOUSE_PASSWORD: ""
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8123/ping" ]
            interval: 5s
            timeout: 10s
            retries: 10
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    clickhouse_data:
        driver: local
